### ISSUE TITLE
japanse language 

### ISSUE THREAD

**Issue by ngksai93** [dveselov/python-yandex-translate#8]
when use this for English to Japanese translation it gives output as 

 u'en-ja', u'text': [u'\u306e\u51fa\u529b\u3053\u306e\u30b3\u30de\u30f3\u30c9\u306f\u8868\u793a\u3059\u3079\u3066\u306e\u30c6\u30ad\u30b9\u30c8\u5185\u306e\u30d5\u30a1\u30a4\u30eb\n\u540c\u3058\u30c6\u30ad\u30b9\u30c8\u307e\u305f\u306f\u901a\u8a33\u3092\u8ffd\u52a0\u3002\n\u5fc5\u8981\u306f\u3042\u308a\u307e\u305b\u3093\u304c\u66f8\u3067\u3059\u3079\u3066\u306e\u884c\u304c\u306a\u3051\u308c\u3070\u306a\u3089\u306a\u3044\u3059\u3079\u3066\u8868\u793a\n'], u'code

how to translate it to Japanese

**Comment by hAirypAulsAck** [comment]
I think it has something to do with your console, maybe code page.. I experienced the same thing when I was working with russian

**Comment by dveselov** [comment]
Use python 3.
